version: "3.9"

services:
   postgres:
    image: postgres:16
    container_name: featuregate_postgres
    restart: always
    environment:
      POSTGRES_DB: featuregate
      POSTGRES_USER: featuregate
      POSTGRES_PASSWORD: featuregate
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

   redis:
    image: redis:7
    container_name: featuregate_redis
    ports:
      - "6379:6379"

   api:
    build:
      context: .
      dockerfile: FeatureGate.Api/Dockerfile
    container_name: featuregate_api
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
    depends_on:
      - postgres
      - redis

volumes:
  pgdata:
